mqtt:
  enabled: false

detectors:
  coral:
    type: edgetpu
    device: usb

# go2rtc: define all main/sub
go2rtc:
  streams:
    # FRONT camera
    front_main: rtsp://smick777:Ydwi3sa2@192.168.68.25:554/h264Preview_01_main
    front_sub: rtsp://smick777:Ydwi3sa2@192.168.68.25:554/h264Preview_01_sub

    # DRIVEWAY camera (already had /11 and /12)
    driveway_main: rtsp://smick777:Ydwi3sa2@192.168.68.24/11
    driveway_sub: rtsp://smick777:Ydwi3sa2@192.168.68.24/12

    # GARAGE camera
    garage_main: rtsp://smick777:Ydwi3sa2@192.168.68.47/11
    garage_sub: rtsp://smick777:Ydwi3sa2@192.168.68.47/12

    # SHED camera
    shed_main: rtsp://smick777:Ydwi3sa2@192.168.68.20/11
    shed_sub: rtsp://smick777:Ydwi3sa2@192.168.68.20/12

    # SPARE camera (already done)
    spare_main: rtsp://smick777:Ydwi3sa2@192.168.68.60/11
    spare_sub:  rtsp://smick777:Ydwi3sa2@192.168.68.60/12

# -------------------------------------
# Cameras section referencing go2rtc
# -------------------------------------
cameras:
  front:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front_main
          roles:
            - record
        - path: rtsp://localhost:8554/front_sub
          roles:
            - detect
    detect:
      enabled: true
      width: 640      # This is the substream resolution output configured in the camera URL http://192.168.68.60/web/admin.html
      height: 352
    record:
      enabled: true
    motion:
      mask:
        - 0.996,0.295,0.855,0.163,0.732,0.124,0.602,0.096,0.597,0.07,0.482,0.033,0.439,0,1,0

  driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/driveway_main
          roles:
            - record
        - path: rtsp://localhost:8554/driveway_sub
          roles:
            - detect
    detect:
      enabled: true
      # Match substream resolution if 640x360, or keep 1280x720 if you truly want that
      width: 640
      height: 352
    record:
      enabled: true
    motion:
      mask:
        - 0,0.08,0.13,0.046,0.452,0.06,0.723,0.095,0.844,0.119,0.925,0.142,0.998,0.183,1,0,0,0

  garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/garage_main
          roles:
            - record
        # If you have a substream:
        - path: rtsp://localhost:8554/garage_sub
          roles:
            - detect
    detect:
      enabled: true  # As you had before
      width: 640      # Or 1280 if you prefer
      height: 352
    record:
      enabled: true  # if you want to record the main stream

  shed:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/shed_main
          roles:
            - record
        # If a substream is available:
        - path: rtsp://localhost:8554/shed_sub
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 352
    record:
      enabled: true
    motion:
      mask:
        - 0.166,0.024,0.117,0.09,0.126,0.199,0.158,0.245,0.219,0.175,0.219,0.088
        - 0.23,0.235,0.288,0.148,0.38,0.152,0.382,0.207,0.346,0.276,0.248,0.362

  spare: # <------ Name the camera
    enabled: true

    # This tells Frigate which input role to use for live view
    # live:
    #   stream_name: spare_main

    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/spare_main  # main stream, high res
          roles:
            - record
        - path: rtsp://localhost:8554/spare_sub   # sub stream, low res
          roles:
            - detect
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 640
      height: 352
    record:
      enabled: true # <---- disable detection until you have a working camera feed

camera_groups:
  Overview:
    order: 1
    icon: LuBird
    cameras:
      - driveway
      - front
      - shed
      - garage
      - spare
version: 0.14
